services:
  backend:
    image: mostafaelmasry/organization-management-system
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - DB_HOST=mongo
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
