version: '3.8'

services:
  backend:
    image: myapp:latest
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=localhost
      - DB_HOST=localhost
      - REDIS_HOST=localhost
    depends_on:
      - mongo
      - redis
    networks:
      - my-network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
